import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
file1=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\Customer_Dataset.csv")
file2=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\products_dataset.csv")
file3=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\sellers_dataset.csv")
file4=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\orders_dataset.csv")
file5=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\order_items_dataset.csv")
file6=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\order_payments_dataset.csv")
file7=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\order_reviews_dataset.csv")
file8=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\category_name_translation.csv")
file25=pd.merge(file2,file5,on="product_id",how="inner")
file258=pd.merge(file25,file8,on="product_category_name",how="inner")
script_dir=os.path.dirname(os.path.abspath(__file__))
save=os.path.join(script_dir,"Graphs")
def Data_Assessment():
    print(file1.head())
    print(file2.head())
    print(file3.head())
    print(file4.head())
    print(file5.head())
    print(file6.head())
    print(file7.head())
    print(file1.dtypes)
    print(file2.dtypes)
    print(file3.dtypes)
    print(file4.dtypes)
    print(file5.dtypes)
    print(file6.dtypes)
    print(file7.dtypes)
    print(file1.isnull().sum())
    print(file2.isnull().sum()) #Product Category Name has 610 null values
    print(file3.isnull().sum())
    print(file4.isnull().sum())
    print(file5.isnull().sum())
    print(file6.isnull().sum())
    print(file7.isnull().sum())
    print(file1[file1.duplicated()])
    print(file2[file2.duplicated()])
    print(file3[file3.duplicated()])
    print(file4[file4.duplicated()])
    print(file5[file5.duplicated()])
    print(file6[file6.duplicated()])
    print(file7[file7.duplicated()])
def Customer_Analysis():
    file14=pd.merge(file1,file4,on="customer_id",how="inner")
    sns.set_style("whitegrid")
    count1=file14["customer_city"].value_counts().head(10).index
    sns.countplot(data=file14[file14["customer_city"].isin(count1)],y="customer_city",hue="customer_city",palette="viridis",legend=False)
    plt.xlabel("No. Of Orders Placed", fontweight="bold")
    plt.ylabel("Customer City", fontweight="bold")
    plt.title("Top 10 City With Highest No. Of Orders Placed", fontweight="bold")
    plt.savefig(os.path.join(save,"Top_10_city_orders.png"),dpi=300)
    plt.show()
    count2=file14["customer_state"].value_counts().head(10).index
    sns.countplot(data=file14[file14["customer_state"].isin(count2)],y="customer_state",hue="customer_state",palette="viridis",legend=False)
    plt.xlabel("No. Of Orders Placed", fontweight="bold")
    plt.ylabel("Customer State", fontweight="bold")
    plt.title("Top 10 State With Highest No. Of Orders Placed", fontweight="bold")
    plt.savefig(os.path.join(save,"Top_10_state_orders.png"),dpi=300)
    plt.show()
    not_delivered = file14[file14["order_status"] != "delivered"]
    count3= not_delivered["customer_city"].value_counts().head(5).index.tolist()
    sns.countplot(data=not_delivered[not_delivered["customer_city"].isin(count3)],x="order_status",hue="customer_city",order=not_delivered["order_status"].value_counts().index)
    plt.xlabel("Order Status", fontweight="bold")
    plt.ylabel("No. Of Orders", fontweight="bold")
    plt.legend(title="City")
    plt.title("Top 5 Cities With Orders Not Yet Delivered", fontweight="bold")
    plt.savefig(os.path.join(save,"Top_10_city_not_delivered.png"),dpi=300)
    plt.show()
    count4= not_delivered["customer_state"].value_counts().head(5).index.tolist()
    sns.countplot(data=not_delivered[not_delivered["customer_state"].isin(count4)],x="order_status",hue="customer_state",order=not_delivered["order_status"].value_counts().index)
    plt.xlabel("Order Status", fontweight="bold")
    plt.ylabel("No. Of Orders", fontweight="bold")
    plt.legend(title="State")
    plt.title("Top 5 States With Orders Not Yet Delivered", fontweight="bold")
    plt.savefig(os.path.join(save,"Top_10_state_not_delivered.png"),dpi=300)
    plt.show()
def Product_analysis():
    file = file258.dropna().copy()
    sns.set_style("whitegrid")
    count1=file["product_category_name_english"].value_counts().head(10).index
    sns.countplot(data=file[file["product_category_name_english"].isin(count1)],y="product_category_name_english",hue="product_category_name_english",order=count1,palette="viridis")
    plt.xlabel("No. Of Orders", fontweight="bold")
    plt.ylabel("Product Category", fontweight="bold")
    plt.title("Top 10 Most Ordered Product Categories", fontweight="bold")
    plt.savefig(os.path.join(save,"Top10_mostordered_product_categories.png"),dpi=300)
    plt.show()
    sns.scatterplot(data=file,x="product_weight_g",y="freight_value",color="darkcyan")
    plt.xlabel("Product Weight In Grams", fontweight="bold")
    plt.ylabel("Freight Value", fontweight="bold")
    plt.title("Product Freight Value And Weight Correlation", fontweight="bold")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Product_weight-Freight_value.png"),dpi=300)
    plt.show()
def Seller_Analysis():
    file35=pd.merge(file3,file5,on="seller_id",how="inner")
    sns.set_style("whitegrid")
    count1=file35["seller_city"].value_counts().head(10).index
    sns.countplot(data=file35[file35["seller_city"].isin(count1)],y="seller_city",hue="seller_city",order=count1,palette="viridis",legend=False)
    plt.xlabel("No. Of Orders", fontweight="bold")
    plt.ylabel("Seller CIty Name", fontweight="bold")
    plt.title("Top 10 Highest Selling Cities", fontweight="bold")
    plt.savefig(os.path.join(save,"TOp10highestsellingcities.png"),dpi=300)
    plt.show()
    count2=file35["seller_state"].value_counts().head(10).index
    sns.countplot(data=file35[file35["seller_state"].isin(count2)],y="seller_state",hue="seller_state",order=count2,palette="viridis",legend=False)
    plt.xlabel("No. Of Orders", fontweight="bold")
    plt.ylabel("Seller State Name", fontweight="bold")
    plt.title("Top 10 Highest Selling States", fontweight="bold")
    plt.savefig(os.path.join(save,"TOp10highestsellingstates.png"),dpi=300)
    plt.show()
    file35["revenue"]=file35["price"]+file35["freight_value"]
    revenue=(file35.groupby("seller_city")["revenue"].sum().sort_values(ascending=False).head(10).reset_index())
    sns.barplot(data=revenue,y="seller_city",x="revenue",hue="seller_city",palette="viridis",legend=False)
    plt.xlabel("Total Revenue Generated In Millions", fontweight="bold")
    plt.ylabel("Seller City", fontweight="bold")
    plt.title("Top 10 Cities With Highest Revenue", fontweight="bold")
    plt.savefig(os.path.join(save,"TOp10highestrevenuecities.png"),dpi=300)
    plt.show()
    revenues=(file35.groupby("seller_state")["revenue"].sum().sort_values(ascending=False).head(10).reset_index())
    sns.barplot(data=revenues,y="seller_state",x="revenue",hue="seller_state",palette="viridis",legend=False)
    plt.xlabel("Total Revenue Generated In 10 Millions", fontweight="bold")
    plt.ylabel("Seller State", fontweight="bold")
    plt.title("Top 10 States With Highest Revenue", fontweight="bold")
    plt.savefig(os.path.join(save,"TOp10highestrevenuestate.png"),dpi=300)
    plt.show()
def Payment_Analysis():
    sns.set_style("whitegrid")
    count1=file6["payment_type"].value_counts().head(4).index
    sns.countplot(data=file6[file6["payment_type"].isin(count1)],x="payment_type",color="turquoise")
    plt.xlabel("Payment Mode", fontweight="bold")
    plt.ylabel("No. Of Orders", fontweight="bold")
    plt.title("Most Common Payment Mode", fontweight="bold")
    plt.savefig(os.path.join(save,"mostcommonpaymentmode.png"),dpi=300)
    plt.show()
    count2=file6["payment_installments"].value_counts().head(5).index
    sns.countplot(data=file6[file6["payment_installments"].isin(count2)],y="payment_installments",hue="payment_type",palette="viridis")
    plt.ylabel("Payment Installments", fontweight="bold")
    plt.xlabel("No. Of Orders", fontweight="bold")
    plt.title("Most Common Installment Plans", fontweight="bold")
    plt.legend(title="Payment Mode")
    plt.savefig(os.path.join(save,"mostcommoninstallmentplans.png"),dpi=300)
    plt.show()
    count3=file6["payment_sequential"].value_counts().head(3).index
    sns.countplot(data=file6[file6["payment_sequential"].isin(count3)],x="payment_sequential",hue="payment_type",palette="viridis")
    plt.xlabel("Payment Sequential", fontweight="bold")
    plt.ylabel("No. Of Orders", fontweight="bold")
    plt.title("Most Common Payment Sequential", fontweight="bold")
    plt.legend(title="Payment Mode")
    plt.savefig(os.path.join(save,"mostcommonsequentials.png"),dpi=300)
    plt.show()
def Review_Analysis():
    file257 = pd.merge(file25, file7, on="order_id", how="inner")
    file2573 = pd.merge(file257, file3, on="seller_id", how="inner")
    sns.set_style("whitegrid")
    top10 = file2573["seller_city"].value_counts().head(10).index
    f1 = file2573[file2573["seller_city"].isin(top10)]
    f1["average_review"] = f1.groupby("seller_city")["review_score"].transform("mean")
    averagereview = (f1.groupby("seller_city")["average_review"].mean().sort_values(ascending=False).head(10).reset_index())
    sns.barplot(data=averagereview, y="seller_city", x="average_review", palette="viridis")
    plt.xlabel("Average Review Score", fontweight="bold")
    plt.ylabel("Seller City", fontweight="bold")
    plt.title("Top 10 High-Volume Seller Cities With Average Review Score", fontweight="bold")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Seller_city_review.png"),dpi=300)
    plt.show()
    top10 = file2573["seller_state"].value_counts().head(10).index
    f2 = file2573[file2573["seller_state"].isin(top10)]
    f2["average_review"] = f2.groupby("seller_state")["review_score"].transform("mean")
    averagereview = (f2.groupby("seller_state")["average_review"].mean().sort_values(ascending=False).head(10).reset_index())
    sns.barplot(data=averagereview, y="seller_state", x="average_review", palette="viridis")
    plt.xlabel("Average Review Score", fontweight="bold")
    plt.ylabel("Seller State", fontweight="bold")
    plt.title("Top 10 High-Volume Seller States With Average Review Score", fontweight="bold")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Seller_state_review.png"),dpi=300)
    plt.show()
    file25738=pd.merge(file2573,file8,on="product_category_name",how="inner")
    top10 = file25738["product_category_name_english"].value_counts().head(10).index
    f3 = file25738[file25738["product_category_name_english"].isin(top10)]
    f3["average_review"] = f3.groupby("product_category_name_english")["review_score"].transform("mean")
    averagereview = (f3.groupby("product_category_name_english")["average_review"].mean().sort_values(ascending=False).head(10).reset_index())
    sns.barplot(data=averagereview, y="product_category_name_english", x="average_review", palette="viridis")
    plt.xlabel("Average Review Score", fontweight="bold")
    plt.ylabel("Product Category", fontweight="bold")
    plt.title("Top 10 High-Volume Product Categories With Average Review Score", fontweight="bold")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"productcategory_review.png"),dpi=300)
    plt.show()
Data_Assessment()
Customer_Analysis()
Product_analysis()
Seller_Analysis()
Payment_Analysis()
Review_Analysis()
